config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todolists
  root 'dashboard#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, Todolist, user_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
  belongs_to :user

  STATUS = ["New", "InProgress", "Done"]
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todolists, dependent: :destroy
  def admin?
    has_role?(:admin)
  end

  def client?
    has_role?(:client)
  end

  def self.assigned_dev(id)
    find(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  load_and_authorize_resource
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @todolists = Todolist.all
    @users = User.all
    @hash_new = {}
    @hash_inProg = {}
    @hash_Done = {}
    @users.each do |key, value |
      if key.todolists.empty?
       @hash_new[key] = []
       @hash_inProg[key] = []
      else
        @hash_new[key] = key.todolists.collect{|i| i.status == 'New'? i.name : [] }.flatten
        @hash_inProg[key] = key.todolists.collect{|i| i.status == 'InProgress'? i.name : [] }.flatten
        @hash_Done[key] = key.todolists.collect{|i| i.status == 'Done' ? i.name :  [] }.flatten
      end
    end
  end

  def show
  end

  def new
    @todolist = Todolist.new
  end

  def edit
  end

  def create
    @todolist = Todolist.new(todolist_params)
    @todolist.user = User.assigned_dev(params[:todolist].dig(:user_id))
    if @todolist.save
      redirect_to todolists_url, notice: 'Todolist was successfully created.'
    else
      render :new
    end
  end

  def update
    if @todolist.update(todolist_params)
      redirect_to @todolist, notice: 'Todolist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @todolist.destroy
    redirect_to todolists_url, notice: 'Todolist was successfully destroyed.'
  end

  private
  def set_todolist
    @todolist = Todolist.find(params[:id])
  end

  def todolist_params
    params.require(:todolist).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
        concat(content_tag(:button, id: "close-button", class: "close", type: :button, data: { dismiss: 'alert' }, "aria-label" => :Close) do
          concat content_tag(:span, "&times;".html_safe, "aria-hidden" => true)
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<%= flash_messages %>
<div class="block">
	<header class="header-group">
		<h2>Welcome to Project Managment Software.</h2>
	</header>
	<div class="row">
		<div class="col-md-12">
		</div>
	</div>
	
	<div class="row" style="margin-top:150px">
		
		<%if !current_user.nil? && current_user.has_role?(:admin) %>
			<div class="col-md-6">
				<h1>Charts on based on projects</h1>
				<%= pie_chart Todolist.group(:status).count %>
			</div>
			
			<div class="col-md-6">
				<h1>Charts on based on developer</h1>
				<%= column_chart Todolist.joins(:user).group(:username).count %>
			</div>
		<%end%>
	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
		<div class="container-fluid">
		  <div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/">Work Managment</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Todolists <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "List", todolists_path %></li>
                  <li><%= link_to "New", new_todolist_path %></li>
                </ul>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                  <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
                <% if user_signed_in? %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
		 	</div>
	  </div>
	</nav>
	<div id="main-container" class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/todolists/_admin_page.html.erb
<h2>Todolists List</h2>
  <div class="todolist-block">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th class="col-md-2">Status</th>
          <% @users.each  do |user|%>
            <th class="col-md-2"><%= user.username%></th>
          <%end%>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td>New</td>
            <%@hash_new.each do |key, value| %>
              <td class="col-md-2">
                <%= 
                  value.each do |list| 
                    list
                  end
                  %>
              </td>
            <%end%>
          </tr>
          <tr>
            <td>In Progress</td>
            <%@hash_inProg.each do |key, value| %>
              <td class="col-md-2">
                <%= 
                  value.each do |list| 
                    list
                  end
                  %>
              </td>
            <%end%>
          </tr>
          <tr>
              <td>Done</td>
              <%@hash_Done.each do |key, value| %>
                <td class="col-md-2">
                  <%= 
                    value.each do |list| 
                      list
                    end
                  %>
                </td>
              <%end%>
            </tr>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Todolist', new_todolist_path, class: "btn btn-primary" %>

app/views/todolists/_form.html.erb
<%= form_for(@todolist) do |f| %>
  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>
      <ul>
      <% @todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :status %><br>
      <%= f.select :status, Todolist::STATUS.map { |s| [I18n.t("status.#{s}"), s] }, :include_blank => false %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :user %><br>
      <%= f.collection_select :user_id, User.order(:username),:id,:username, :include_blank => 'Please Assign a Developer' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h2>Editing Todolist</h2>

<%= render 'form' %>

<%= link_to 'Show', @todolist, class: "btn btn-warning" %>
<%= link_to 'Back', todolists_path, class: "btn btn-default" %>

app/views/todolists/index.html.erb
<%if  current_user.admin? %>
<%=  render partial: "admin_page.html.erb"%>
<%else%>

  <%= flash_messages %>

  <h2>User Todolists List </h2>
  <div class="todolist-block">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th class="col-md-2">Status</th>
          <th class="col-md-2"><%= current_user.username%></th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td>New</td>
            <%@hash_new.each do |key, value| %>
              <%if key == current_user%>
                <td class="col-md-2">
                  <%= 
                    value.each do |list| 
                      list
                    end
                  %>
                </td>
              <%end%>
            <%end%>
          </tr>
          <tr>
            <td>In Progress</td>
            <%@hash_inProg.each do |key, value| %>
             <%if key == current_user%>
                <td class="col-md-2">
                  <%= 
                    value.each do |list| 
                      list
                    end
                  %>
                </td>
              <%end%>
            <%end%>
          </tr>
          <tr>
              <td>Done</td>
              <%@hash_Done.each do |key, value| %>
              <%if key == current_user%>
                  <td class="col-md-2">
                    <%= 
                      value.each do |list| 
                        list
                      end
                    %>
                  </td>
                <%end%>
              <%end%>
            </tr>
      </tbody>
    </table>
  </div>

  <br>
<%end%>

app/views/todolists/new.html.erb
<h2>New Todolist</h2>

<%= render 'form' %>

<%= link_to "Back", todolists_path, class: "btn btn-default" %>

app/views/todolists/show.html.erb
<%= flash_messages %>
<h2>Todolist</h2>

<p>
  <strong>Name:</strong>
  <%= @todolist.name %>
</p>

<p>
  <strong>status:</strong>
  	$<%= @todolist.status %>
</p>

<%= link_to 'Edit', edit_todolist_path(@todolist), class: "btn btn-warning" %>
<%= link_to "Back", todolists_path, class: "btn btn-default" %>